project_diplom/cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:id>', views.cart_add, name='cart_add'),
    path('remove/<int:id>', views.cart_remove, name='cart_remove')
]

project_diplom/order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

project_diplom/project_diplom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project_diplom import views
from .views import Search

from project_diplom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_page.urls'), name='first_page'),
    path('bicycle/', include('bicycle.urls'), name='bicycle'),
    path('cart/', include('cart.urls'), name='cart'),
    path('auth/', include('authentication.urls'), name='auth'),
    path('order/', include('order.urls'), name='order'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('payments/', include('payments.urls'), name='payments'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_diplom/order/models.py
from django.db import models

from bicycle.models import Product


# Определяем модель для заказов.
class Order(models.Model):
    # Имя заказчика (строка, максимум 50 символов).
    first_name = models.CharField(max_length=50)
    # Фамилия заказчика (строка, максимум 50 символов).
    last_name = models.CharField(max_length=50)
    # Email заказчика.
    email = models.EmailField()
    # Адрес заказа (строка, максимум 250 символов).
    address = models.CharField(max_length=250)
    # Почтовый индекс заказа (строка, максимум 20 символов).
    postal_code = models.CharField(max_length=20)
    # Город заказа (строка, максимум 100 символов).
    city = models.CharField(max_length=100)
    # Дата и время создания заказа (автоматически устанавливается при создании).
    created = models.DateTimeField(auto_now_add=True)
    # Дата и время последнего обновления заказа (автоматически обновляется при изменениях).
    updated = models.DateTimeField(auto_now=True)
    # Признак оплаты заказа (по умолчанию False, т.е. неоплачен).
    paid = models.BooleanField(default=False)

    # Мета-класс для определения метаданных модели.
    class Meta:
        # Сортировка заказов по умолчанию - в обратном порядке по дате создания.
        ordering = ('-created',)
        # Наименование модели в единственном числе.
        verbose_name = 'Заказ'
        # Наименование модели во множественном числе.
        verbose_name_plural = 'Заказы'

    # Метод, возвращающий строковое представление заказа.
    def __str__(self):
        return 'Order {}'.format(self.id)

    # Метод для вычисления общей стоимости заказа.
    def get_total_cost(self):
        # Суммируем стоимость каждого элемента заказа, умноженную на его количество.
        return sum(item.get_cost() for item in self.items.all())


# Определяем модель для элементов заказа.
class OrderItem(models.Model):
    # Ссылка на заказ (связь "многие к одному" с моделью Order).
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    # Ссылка на продукт (связь "многие к одному" с моделью Product).
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    # Цена элемента заказа (десятичное число с 10 знаками и 2 знаками после запятой).
    price = models.DecimalField(max_digits=10, decimal_places=2)
    # Количество продуктов в заказе (целое положительное число, по умолчанию 1).
    quantity = models.PositiveIntegerField(default=1)

    # Метод, возвращающий строковое представление элемента заказа.
    def __str__(self):
        return '{}'.format(self.id)

    # Метод для вычисления стоимости элемента заказа.
    def get_cost(self):
        # Вычисляем общую стоимость элемента (цена * количество).
        return self.price * self.quantity

project_diplom/order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

project_diplom/order/views.py
from django.shortcuts import render

from cart.cart import Cart
from .forms import OrderCreateForm
from .models import OrderItem


# Создаем представление для создания заказа
def order_create(request):
    # Получаем корзину текущего пользователя
    cart = Cart(request)

    if request.method == 'POST':
        # Если запрос методом POST, создаем форму заказа и передаем данные из запроса
        form = OrderCreateForm(request.POST)

        # Проверяем, что данные формы прошли валидацию
        if form.is_valid():
            # Если форма действительна, создаем объект заказа, но не сохраняем его в базе данных
            order = form.save()

            # Создаем объекты OrderItem для каждого элемента корзины и связываем их с заказом
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])

            # После создания всех OrderItem, очищаем корзину
            cart.clear()

            # Отображаем страницу "created.html" с информацией о заказе
            return render(request, 'created.html', {'order': order})

    else:
        # Если запрос не методом POST, создаем пустую форму заказа
        form = OrderCreateForm()

    # Отображаем страницу "create.html" с данными о корзине и формой заказа
    return render(request, 'create.html', {'cart': cart, 'form': form})

project_diplom/order/templates/create.html
{% extends "base.html" %}
{% block title %}Оформление заказа{% endblock title %}

{% block content %}
<div class="container-fluid py-5 text-center">
    <div class="row">
        <div class="col-md-6 m-auto text-center">
            <h1 class="h1" style="padding-top: 100px;">Оформление заказа</h1>
        </div>
        <div class="order-info text-center">
            <h3 class="text-center">Ваш заказ</h3>
            {% for item in cart %}
            <li style="list-style-type: none;">
                <p>Количество: {{ item.quantity }}</p>
                <p>{{ item.product.name }}</p>
            </li>
            {% endfor %}
        </div>
        <p>Всего: Br {{ cart.get_total_price }}</p>
        <form action="." method="post" class="order-form">
            <div class="row">
                <div class="col-12 col-lg-4 col-md-4 offset-md-4">
                    <div class="quote-form-wrapper">
                        <label class="order-form" for="id_firstname"></label>
                        <input type="text" class="form-input" placeholder="Имя"
                               id="id_firstname" name="first_name" required>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-12 col-lg-4 col-md-4 offset-md-4">
                    <div class="quote-form-wrapper">
                        <label class="order-form" for="id_lastname"></label>
                        <input type="text" class="form-input" placeholder="Фамилия"
                               id="id_lastname" name="last_name" required>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-12 col-lg-4 col-md-4 offset-md-4">
                    <div class="quote-form-wrapper">
                        <label class="order-form" for="id_email"></label>
                        <input type="text" class="form-input" placeholder="Email"
                               id="id_email" name="email" required>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-12 col-lg-4 col-md-4 offset-md-4">
                    <div class="quote-form-wrapper">
                        <label class="order-form" for="id_address"></label>
                        <input type="text" class="form-input" placeholder="Адрес"
                               id="id_address" name="address" required>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-12 col-lg-4 col-md-4 offset-md-4">
                    <div class="quote-form-wrapper">
                        <label class="order-form" for="id_postalcode"></label>
                        <input type="text" class="form-input" placeholder="Почтовый код"
                               id="id_postalcode" name="postal_code" required>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-12 col-lg-4 col-md-4 offset-md-4">
                    <div class="quote-form-wrapper">
                        <label class="order-form" for="id_city"></label>
                        <input type="text" class="form-input" placeholder="Город"
                               id="id_city" name="city" required>
                    </div>
                </div>
            </div>
            <br>
            <form action="{% url 'charge' %}" method="post">
                {% csrf_token %}
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button">
                    data-key="{{ key }}"
                    data-description="Payment"
                    data-amount= {{ item.price }}
                    data-locale="auto"
                </script>
            </form>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock %}

project_diplom/order/templates/created.html
{% extends "base.html" %}
{% block title %}Thank you{% endblock title %}

{% block content %}
    <h1 class="text-center" style="padding-top: 250px;">Спасибо!</h1>
    <h3 class="text-center">Ваш заказ успешно создан. Номер заказа - Order
        <strong>{{ order.id }}</strong>.</h3>
{% endblock %}