project_diplom/bicycle/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.product_index, name='product_index'),
    path('<int:id>/', views.product_detail, name='product_detail'),
]

project_diplom/cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:id>', views.cart_add, name='cart_add'),
    path('remove/<int:id>', views.cart_remove, name='cart_remove')
]

project_diplom/project_diplom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project_diplom import views
from .views import Search

from project_diplom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_page.urls'), name='first_page'),
    path('bicycle/', include('bicycle.urls'), name='bicycle'),
    path('cart/', include('cart.urls'), name='cart'),
    path('auth/', include('authentication.urls'), name='auth'),
    path('order/', include('order.urls'), name='order'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('payments/', include('payments.urls'), name='payments'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_diplom/bicycle/models.py
from django.db import models


class Category(models.Model):
    # Модель "Category" - категория продукта.
    name = models.CharField(max_length=255, blank=True, null=True, default=None)

    # Поле "name" типа "CharField" для хранения имени категории.

    def __str__(self):
        # Метод "__str__" возвращает строковое представление объекта модели.
        return self.name


class Product(models.Model):
    # Модель "Product" - продукт.
    article = models.CharField(max_length=10, blank=True, null=True, default=None)
    # Поле "article" типа "CharField" для хранения артикула продукта.
    name = models.CharField(max_length=255, blank=True, null=True, default=None)
    # Поле "name" типа "CharField" для хранения имени продукта.
    description = models.TextField(blank=True, null=True, default=None)
    # Поле "description" типа "TextField" для хранения описания продукта.
    stock = models.PositiveIntegerField()
    # Поле "stock" типа "PositiveIntegerField" для хранения количества продукта на складе.
    price = models.DecimalField(max_digits=7, decimal_places=2)
    # Поле "price" типа "DecimalField" для хранения цены продукта.
    image = models.ImageField(upload_to='img/', blank=True, null=True, default=None)
    # Поле "image" типа "ImageField" для хранения изображения продукта.
    available = models.BooleanField(default=True)
    # Поле "available" типа "BooleanField" для хранения информации о доступности продукта.
    cat = models.ForeignKey('Category', models.CASCADE, blank=True, null=True, default=None)
    # Поле "cat" типа "ForeignKey" для связи продукта с категорией. Каскадное удаление связанных объектов.
    created = models.DateTimeField(auto_now_add=True)
    # Поле "created" типа "DateTimeField" для хранения даты и времени создания записи о продукте.
    # Автоматически заполняется при создании.
    updated = models.DateTimeField(auto_now=True)

    # Поле "updated" типа "DateTimeField" для хранения даты и времени последнего обновления записи о продукте.
    # Автоматически обновляется при сохранении объекта.

    def __str__(self):
        # Метод "__str__" возвращает строковое представление объекта модели.
        return self.name

project_diplom/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

project_diplom/bicycle/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from cart.forms import CartAddProductForm
from .models import Product, Category

@cache_page(60 * 15)
def product_index(request):
    """
    Представление для отображения списка продуктов (индексной страницы).

    Основные действия:
    1. Получает все категории товаров из базы данных.
    2. Получает все доступные продукты из базы данных.
    3. Создает контекст с данными о категориях и продуктах.
    4. Возвращает ответ с отображением шаблона "product_index.html" и контекстом.
    """
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    context = {
        'categories': categories,
        'products': products,
    }
    return render(request, 'product_index.html', context)


def product_detail(request, id):
    """
    Представление для отображения деталей конкретного продукта.

    Основные действия:
    1. Получает продукт с заданным id из базы данных.
    2. Если продукт не найден или недоступен (available=False), вернет ошибку 404.
    3. Инициализирует форму CartAddProductForm для добавления продукта в корзину.
    4. Создает контекст с данными о продукте и формой.
    5. Возвращает ответ с отображением шаблона "product_detail.html" и контекстом.
    """
    product = get_object_or_404(Product, id=id, available=True)
    cart_product_form = CartAddProductForm()

    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'product_detail.html', context)

project_diplom/bicycle/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/card_detail.css' %}">
<div class="row">
    <div class="col-md-6">
        <img src="{{ product.image.url }}" alt="Error" width=76%>
    </div>
   <div class="co-md-2" style="height:500px;">
       <h5> Описание: </h5>
       <h6>Категория: {{product.cat}}</h6>
       <p> {{ product.description }}</p>
       <br>
       <h5>Цена:</h5>
       <p>{{ product.price }} р</p>
       <h6>Артикул: {{ product.article}}</h6>
       <br>
       <div>
           <form action="{% url 'cart_add' product.id %}" class="form-inline" method="post">
               {% csrf_token %}
               <h5>Количество</h5>
                <label class="form-label" for="id_quantity"></label>
                <input type="button" class="btn btn-secondary" value="-" onClick="change('amount',0,10,-1);"/>
                <input id="amount" type="text" value="1" id="id_quantity" name="quantity"/>
                <input type="button" class="btn btn-secondary" value="+" onClick="change('amount',0,10, 1);"/></h5>
                <input type="submit" class="btn btn-dark" value="Добавить в корзину">
           </form>
       </div>
   </div>
</div>
<script src="{% static '/js/scripts.js' %}"></script>
{% endblock %}

project_diplom/bicycle/templates/product_index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Качественные велосипеды от именитых производителей {% endblock %}
{% block content %}
<center>
    <h1>Каталог</h1>

    <div class="container py-5">
        <div class="row">
            {% for product in products %}
            <div class="col-12 col-md-4 mb-4">
                <div class="card h-100">
                    <p class="aligncenter">
                        {% if product.image %}
                        <p><img src="{{ product.image.url }}" alt="" width="70%"></p>
                        {% else %}
                        <p></p>
                        {% endif %}
                    </p>
                    <style>.aligncenter {text-align: center;}</style>
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <h5 class="card-title">Категория: {{ product.cat }}</h5>
                        <h6 class="card-text">Цена: {{ product.price }} р</h6>

                        <a href="{% url 'product_detail' product.id %}"
                           class="btn btn-dark">
                            Подробнее
                        </a>

                    </div>

                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</center>
{% endblock %}
<!--<h1>Компоненты</h1>-->
<!--<div class="row">-->
<!--    {% for com in components %}-->
<!--    <div class="col-md-4">-->
<!--        <div class="card mb-2">-->
<!--            <img class="card-img-top" src="{{ com.photo.url }}" alt="Надеюсь" width="300px" height="300px">-->
<!--            <div class="card-body">-->
<!--                <h5 class="card-title"> {{ com.name }} </h5>-->
<!--                <p class="card-text"> {{ com.description }}</p>-->
<!--                <a href="{% url 'components_detail' com.pk %}"-->
<!--                class="btn btn-primary">-->
<!--                    Подробнее-->
<!--                </a>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    {% endfor %}-->
<!--</div>-->